config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users

  authenticate :user do
    root to: 'categories#index'

    resources :categories do
      resources :tasks
    end
    resources :tasks
  end

  authenticate :user, lambda { |u| u.admin == true } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title,
    presence: true, uniqueness: true
  validates :description,
    presence: true, length: { in: 10..100 }

  belongs_to :user
  has_many :tasks, dependent: :destroy

  scope :filtered, ->(query_params) { Category::Filter.new.filter(self, query_params) }
end

app/models/category/filter.rb
class Category::Filter
  def filter(scope, query_params)
    if query_params[:title].present?
      scope = scope.where("title ILIKE :title OR description ILIKE :title", title: "%#{query_params[:title]}%")
    end

    scope
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description,
    presence: true, length: { in: 10..100 }

  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @categories = current_user.categories.filtered(query_params).order(updated_at: :desc)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description)
    end

    def query_params
      query_params = params[:query]
      query_params ? query_params.permit(:title, :description) : {}
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @task = @category.tasks.new(task_params)
    @task.user_id = current_user.id
    @task.category_id = @category.id

    @task.save

    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])

    @task.destroy

    redirect_to category_path(@category)
  end

  private
    def task_params
      params.require(:task).permit(:description, :due_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_category.html.haml
%div{id: "category-#{category.id}", class: "card"}
  .card-body
    %h4.card-title
      = link_to category.title, category, data: { bs_toggle: 'modal', bs_target: '#showCategoryModal', remote: false }
    %h6.card-text
      = category.description
    .btn-group
      = link_to 'Edit', edit_category_path(category), data: { bs_toggle: 'modal', bs_target: '#editCategoryModal', remote: true }, class: "btn btn-primary"
      = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "btn btn-danger"
    %table.table.table-bordered.table-hover.table-dark
      %thead
        %tr
          %th Task
          %th Due Date
          %th Status
          %th{:colspan => "3"}
      %tbody
        - category.tasks.each do |task|
          %tr
            %td= task.description
            %td= task.due_date
            %td= task.status
            %td
              = link_to 'Destroy', [task.category, task], confirm: 'Are you sure?', method: :delete

app/views/categories/_form.html.haml
.d-sm-flex.flex-sm-column.p-sm-4
  - @category.tasks.build
  = form_with(model: category, local: false) do |form|
    - if category.errors.any?
      #error_explanation.alert.alert-warning
        %h2
          = pluralize(category.errors.count, "error")
          prohibited this category from being saved:
        %ul
          - category.errors.each do |error|
            %li= error.full_message
    .form-group
      = form.label :title, class: "form-label"
      = form.text_field :title, class: "form-control"
    .form-group
      = form.label :description, class: "form-label"
      = form.text_field :description, class: "form-control"
    .actions
      = form.submit

app/views/categories/create.js.haml
- if @category.errors.any?
  alert('Error');
- else
  $("#categories").prepend("#{escape_javascript render('category', category: @category)}");
  $(".btn-close").click();

app/views/categories/destroy.js.haml
$("#category-#{@category.id}").remove();

app/views/categories/edit.html.haml
%h1 Edit Category
= render 'form', category: @category
.btn-group
  = button_to 'Show', @category, method: :get, class: "btn btn-primary"
  = button_to 'Back', categories_path, method: :get, class: "btn btn-warning"

app/views/categories/edit.js.haml
$("#editCategoryForm").html("#{escape_javascript render('form', category: @category)}");

app/views/categories/index.html.haml
%p#notice= notice

= form_for :query, url: categories_path, method: :get do |f|
  .form-group
    = f.text_field :title, placeholder: 'Search Categories (title or description)', value: params.dig('query', 'title'), class: "form-control"
  .actions
    = f.submit 'Search'

= link_to 'New Category', new_category_path, class: "btn btn-primary", data: { bs_toggle: 'modal', bs_target: '#newCategoryModal', remote: true }

-# new category modal
#newCategoryModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "newCategoryModalLabel", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#newCategoryModalLabel.modal-title New Category
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      #newCategoryForm

-# edit category modal
#editCategoryModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editCategoryModalLabel", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#editCategoryModalLabel.modal-title Edit Category
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      #editCategoryForm

-# show category modal
#showCategoryModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "showCategoryModalLabel", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#showCategoryModalLabel.modal-title Show Category
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      #showCategory

%h1 Categories
#categories
  - @categories.each do |category|
    = render 'category', category: category

app/views/categories/new.html.haml
%h1 New Category
= render 'form', category: @category
= button_to 'Back', categories_path, method: :get, class: "btn btn-warning"

app/views/categories/new.js.haml
$("#newCategoryForm").html("#{escape_javascript render('form', category: @category)}");

app/views/categories/show.html.haml
%p#notice= notice

%p
  %h2
    Title:
    = @category.title
  %h4
    Description:
    = @category.description

%p
  %h2 Tasks
  = render @category.tasks

%p
  %h2 New Task
  = render "tasks/form"

.btn-group
  = button_to 'Edit', edit_category_path(@category), method: :get, class: "btn btn-primary"
  = button_to 'Back', categories_path, method: :get, class: "btn btn-warning"

app/views/categories/show.js.haml
$("#showCategory").html("#{escape_javascript render('category', category: @category)}");

app/views/categories/update.js.haml
- if @category.errors.any?
  alert('Error');
- else
  $("#category-#{@category.id}").replaceWith("#{escape_javascript render('category', category: @category)}");
  $(".btn-close").click();

app/views/layouts/_alerts.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/_navbar.html.haml
.navbar.bg-dark.navbar-dark.fixed-top.navbar-expand-sm
  .container-fluid
    -# brand/logo
    %a.navbar-brand{href: root_path}
      %img.rounded-pill{src: "https://previews.123rf.com/images/dstarky/dstarky1701/dstarky170101282/69424140-journal-icon-or-logo-line-art-style-vector-illustration-isolated-on-white-background-.jpg", alt: "Brand/Logo", style: "width:40px;"}/
    -# collapsible navbar toggler
    %button.navbar-toggler{type: "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#collapsible-navbar"}
      %span.navbar-toggler-icon
    -# collapsible navbar
    #collapsible-navbar.collapse.navbar-collapse.justify-content-around
      -# form
      %form.d-flex
        .input-group
          %input.form-control{type: "text", placeholder: "Search"}/
          = button_to 'Search', {type: "button"}, class: "btn btn-success"
      -# links
      %ul.navbar-nav
        - if current_user
          - if current_user.admin
            %li.nav-item
              = link_to 'Admin', rails_admin_path, class: "nav-link"
          %li.nav-item
            = link_to 'Categories', categories_path, class: "nav-link"
          %li.nav-item
            = link_to 'New category', new_category_path, class: "nav-link"
          %li.nav-item.dropdown
            = link_to 'Account', "#", role: "button", "data-bs-toggle" => "dropdown", class: "nav-link dropdown-toggle"
            %ul.dropdown-menu
              %li
                = link_to current_user.email, "#", class: "dropdown-item"
              %li
                = link_to 'Sign out', destroy_user_session_path, "data-method" => "delete", rel: "nofollow", data: { confirm: 'Are you sure you want to sign out?' }, class: "dropdown-item"
        - else
          %li.nav-item
            = link_to 'Sign in', new_user_session_path, class: "nav-link"
          %li.nav-item
            = link_to 'Sign up', new_user_registration_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Journal
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    -# jQuery
    %script{:crossorigin => "anonymous", :integrity => "sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=", :src => "https://code.jquery.com/jquery-3.6.0.js"}
  %body
    .d-sm-flex.flex-sm-column.p-sm-5
      = render 'layouts/navbar'
      = render 'layouts/alerts'
      = yield

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.erb
- if current_user
  = link_to 'Sign out', destroy_user_session_path, method: :delete
  = link_to 'Categories',categories_path
- else
  = link_to 'Sign up', new_user_registration_path
  = link_to 'Sign in',new_user_session_path

app/views/tasks/_form.html.haml
.d-sm-flex.flex-sm-column.p-sm-4
  = form_for([@category, @category.tasks.build]) do |f|
    .form-group
      = f.label :description, class: "form-label"
      = f.text_field :description, class: "form-control"
    .form-group
      = f.label :due_date, class: "form-label"
      = f.date_field :due_date, class: "form-control"
    .form-group
      = f.label :status, class: "form-label"
      .form-check
        = f.radio_button :status, "unfinished", :checked => true, class: "form-check-input"
        = f.label :status_unfinished if false
        %label{:for => "task_status_unfinished", class: "form-check-label"} Unfinished
      .form-check
        = f.radio_button :status, "in_progress", class: "form-check-input"
        = f.label :status_in_progress if false
        %label{:for => "task_status_in_progress", class: "form-check-label"} In Progress
      .form-check
        = f.radio_button :status, "completed", class: "form-check-input"
        = f.label :status_completed if false
        %label{:for => "task_status_completed", class: "form-check-label"} Completed
    .actions
      = f.submit

app/views/tasks/_task.html.haml
.card
  .card-body
    %p
      %b Task:
      = task.description
    %p
      %b Due Date:
      = task.due_date
    %p
      %b Status:
      = task.status
    = button_to 'Destroy', [task.category, task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"